# Backstage override configuration for your local development environment
backend:
  database:
    # config options: https://node-postgres.com/apis/client
    client: pg
    connection:
      host: localhost
      port: 5432
      user: postgres
      password: secret

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        ## uncomment if using GitHub Enterprise
        # enterpriseInstanceUrl: ${AUTH_GITHUB_ENTERPRISE_INSTANCE_URL} 
        signIn:
          resolvers:
          - resolver: usernameMatchingUserEntityName

integrations:
  github:
    - host: github.com
      apps:
        - $include: github-credentials.yaml
