apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: guest-catalog
  description: An example of guest catalog.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: guests