---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: backstage-sample-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backstage-sample-nginx
  template:
    metadata:
      labels:
        app: backstage-sample-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80