---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstage-postgres-storage-claim
  namespace: backstage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G